### ISSUE TITLE
Wizard Process bar is not working on IE 11

### ISSUE THREAD

**Issue by kranthik2330** [jmpisson/lightning-wizard#2]
Hello,

Wizard flow bar is not working on IE11. Please find my attached screenshot.
do i need to add any additional css to handle in IE?

![ie wizard issue](https://user-images.githubusercontent.com/36719601/91460256-9ea99700-e855-11ea-82ae-fcc2d7747d87.JPG)

**Comment by jmpisson** [comment]
Hi! 

How exactly are you using the component IE11? Through an Aura app or by using Lightning for Visualforce? I'm going to try to replicate this issue to see if I can fix that.

The flow bar is built upon the standard `lightning-progress-bar`, so I'm not sure if anything can be done here - maybe upgrading the component API version could work.

**Comment by kranthik2330** [comment]
I'm using as lightning web component Not Aura.

**Comment by kranthik2330** [comment]
Hello, Are you able to reproduce this issue in IE 11? How can i upgrade component API Version? Can you please provide me steps?

**Comment by jmpisson** [comment]
I reproduced this issue in IE11 - it looks there is some CSS rules that IE11 is not able to apply. I'm afraid there is no easy solution for this; I have upgraded the API version myself in order to test IE11, and the issue is still there.

As the progress bar is from the [standard component library](https://developer.salesforce.com/docs/component-library/bundle/lightning-progress-indicator/example), I could not modify the internal CSS to fix the UI in Internet Explorer, and the only solution I see is to rewrite the component. If you check the standard, you will see the standard does not work either.

I'm going to check how other components from Lightning Experience works on IE11.
